version: "3.9"
services:
  backend:
    build:
      context: ./backend/app
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Map the Nginx port to 3000
    environment:
    - REACT_APP_API_BASE_URL=http://backend:5000
    depends_on:
      - backend
