services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development
      - key: OPENAI_API_KEY
        sync: true  # Ensures it pulls the value from the Render environment settings
    dockerContext: ./backend/app
    dockerfilePath: ./backend/app/Dockerfile
    ports:
      - 5000

  - type: web
    name: frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: http://backend:5000
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    ports:
      - 80
    dependsOn:
      - backend